CC=g++

INCLUDE_PATH:=-I/usr/include \
							-I/usr/local/include

LIBRARY_PATH:=-L/usr/lib \
							-L/usr/share/lib

LIBS:=
	#-llibstlport_static

CFLAGS= -std=c++14 -Wall -static $(INCLUDE_PATH)


SOURCES=$(wildcard src/*.cpp)
OBJECTS=$(patsubst %.cpp,%.o, $(SOURCES))

all: ${OBJECTS}
	${CC} ${CFLAGS} -o pinball ${OBJECTS} ${LIBS}

clean:
	rm -f src/*.o
	rm -f pinball

.cpp.o:
	${CC} ${CFLAGS} ${INCLUDE_PATH} -c $< -o $@
