NDKPATH =
TOOLPATH=
TOOLPREFIX=
SYSROOT=
CC= $(TOOLPREFIX)g++

INCLUDE_PATH:=-I/usr/include
LIBRARY_PATH:=-L/usr/lib
LIBS:=

CFLAGS= -Wall $(INCLUDE_PATH)

SOURCES=$(wildcard src/*.cpp)
OBJECTS=$(patsubst %.cpp,%.o, $(SOURCES))

all: ${OBJECTS}
	${CC} ${CFLAGS} -o pinball ${OBJECTS} ${LIBS}

clean:
	rm -f src/*.o
	rm -f pinball

.cpp.o:
	$(info OBJ $< ($@))
	${CC} ${CFLAGS} ${INCLUDE_PATH} -c $< -o $@
